"""
Pydantic models for API request/response contracts.
Provides typed, validated data structures for the research pipeline.
"""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


class ResearchRequest(BaseModel):
    """Incoming research query from the user."""
    query: str = Field(..., min_length=1, max_length=2000, description="The research question or topic")
    session_id: Optional[str] = Field(default=None, description="Session ID for conversation continuity")


class Citation(BaseModel):
    """A single source citation from RAG or web search."""
    source_name: str = Field(..., description="Name of the source document or URL")
    page_number: Optional[int] = Field(default=None, description="Page number within the source document")
    content_snippet: str = Field(..., description="Relevant excerpt from the source")
    relevance_score: Optional[float] = Field(default=None, description="Similarity/relevance score")


class ResearchReport(BaseModel):
    """Structured research report generated by the Writer agent."""
    title: str = Field(..., description="Report title")
    summary: str = Field(..., description="Executive summary of findings")
    key_findings: list[str] = Field(default_factory=list, description="Bullet-point key findings")
    detailed_analysis: str = Field(default="", description="In-depth analysis")
    recommendations: list[str] = Field(default_factory=list, description="Actionable recommendations")


class AgentStep(BaseModel):
    """A single step in the multi-agent execution pipeline."""
    agent_name: str = Field(..., description="Which agent executed this step")
    action: str = Field(..., description="What the agent did")
    tools_used: list[str] = Field(default_factory=list, description="Tools invoked during this step")


class ResearchResponse(BaseModel):
    """API response containing the full research output."""
    session_id: str = Field(..., description="Session ID for this conversation")
    report: ResearchReport = Field(..., description="The structured research report")
    citations: list[Citation] = Field(default_factory=list, description="All sources cited")
    agent_steps: list[AgentStep] = Field(default_factory=list, description="Execution trace of agents")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the response was generated")


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = "healthy"
    version: str = "2.0.0"


class SessionHistoryResponse(BaseModel):
    """Response for session history endpoint."""
    session_id: str
    turns: list[dict] = Field(default_factory=list, description="List of query-response pairs")
    total_turns: int = 0
